"""xg harness interface — single-turn REPL with session persistence."""

import os
import select
import sys
import termios
import tty
from pathlib import Path

from langchain_core.messages import ToolMessage
from rich.console import Console, Group
from rich.live import Live
from rich.markdown import Markdown
from rich.spinner import Spinner
from rich.text import Text

from xg_project.config import Config, load_project_config
from xg_project.llm import (
    add_message,
    execute_tool,
    stream_turn,
    tool_result,
)
from xg_project.session import (
    append,
    configure,
    create,
    file_context,
    load,
    messages,
)

ESC = "\x1b"


def _write(text: str) -> None:
    os.write(sys.stdout.fileno(), text.encode())


def _clear_line() -> None:
    _write("\r\033[2K")


def _read_key() -> str:
    """Read one logical key, consuming ANSI escape sequences as a unit.

    A bare ESC remains the exit key. CSI/SS3 sequences generated by arrows,
    Home/End, and similar keys are consumed and ignored by the line editor,
    so their bytes cannot leak into the submitted prompt.
    """
    key = os.read(sys.stdin.fileno(), 1).decode("utf-8", errors="replace")
    if key != ESC:
        return key

    # A bare ESC is intentional; an escape sequence has more bytes shortly
    # after it. The short timeout keeps ESC responsive without blocking.
    if not select.select([sys.stdin], [], [], 0.03)[0]:
        return ESC

    prefix = os.read(sys.stdin.fileno(), 1).decode("utf-8", errors="replace")
    if prefix not in ("[", "O"):
        return ""

    # CSI/SS3 sequences terminate with a byte in the final-byte range.
    while True:
        byte = os.read(sys.stdin.fileno(), 1)
        if not byte:
            return ""
        value = byte[0]
        if 0x40 <= value <= 0x7E:
            return ""


def _get_session_dir() -> Path:
    return Path.cwd() / ".xg" / "sessions"


def _readline(initial: str = "", prompt: str = "> ") -> str | None:
    """Read a line. Returns None on ESC, empty string on Enter, or the text."""
    value = list(initial)
    # Keep the interface minimal: a simple prompt, with user text styled.
    _write(prompt + "\033[36m" + initial)
    while True:
        key = _read_key()
        if key == ESC:
            _write("\r\n")
            return None
        if key in ("\r", "\n"):
            if value:
                _write("\033[0m\r\n")
            else:
                # Remove the empty prompt instead of leaving a marker on screen.
                _write("\033[0m\r\033[2K\n")
            return "".join(value)
        if key in ("\x03", "\x04"):
            raise KeyboardInterrupt
        if key in ("\x7f", "\b"):
            if value:
                value.pop()
                _write("\b \b")
            continue
        if key.isprintable():
            value.append(key)
            _write(key + "\033[36m")


def _tool_prompt(
    tool_calls: list[dict[str, object]],
    console: Console,
    approval: Live,
) -> str:
    """Approve, inspect, extract, or replace pending tool calls."""
    instruction = Text("Enter=allow  /v=view  /e=extract command  text=cancel", style="dim")
    # Rich refreshes redraw the terminal and would overwrite the line editor.
    # Pause the display while the user is typing.
    approval.stop()
    while True:
        choice = _readline(prompt="tool> ")
        if choice is None:
            raise SystemExit
        if not choice:
            approval.start()
            return "accept"
        if choice == "/v":
            preview = [instruction]
            for call in tool_calls:
                preview.append(Text(f"{call['name']} {call.get('args', {})}", style="dim"))
            approval.update(Group(*preview))
            approval.start()
            approval.stop()
            continue
        if choice == "/e":
            commands = [
                str(call.get("args", {}).get("command", ""))
                for call in tool_calls
                if call["name"] == "cmd"
            ]
            if not commands:
                console.print("[red]/e is only available for command calls[/red]")
                continue
            os.execvp("/bin/sh", ["sh", "-lc", "\n".join(commands)])  # noqa: S606
        approval.start()
        return f"cancel:{choice}"


def main() -> None:
    console = Console()


    continue_session = os.environ.get("XG_CONTINUE") == "1"
    session_dir = _get_session_dir()

    # Session database lives at ~/.xg/sessions.db (the module default).
    configure()
    project_config = load_project_config(Path.cwd())
    os.environ["XG_PROJECT_ROOT"] = str(Path.cwd().resolve())

    if continue_session:
        try:
            session_path = load(session_dir)
            msgs = list(messages(session_path))
            config = Config(
                session_path=session_path,
                use_gitignore=project_config.use_gitignore,
            )
            console.print("[dim]Resumed the last conversation.[/dim]\n")
        except FileNotFoundError:
            console.print("[yellow]No previous conversation found. Starting new.[/yellow]\n")
            session_path = create(session_dir)
            config = Config(
                session_path=session_path,
                use_gitignore=project_config.use_gitignore,
            )
            msgs = file_context(Path.cwd(), config)
            for msg in msgs:
                append(session_path, msg)
    else:
        session_path = create(session_dir)
        config = Config(
            session_path=session_path,
            use_gitignore=project_config.use_gitignore,
        )
        msgs = file_context(Path.cwd(), config)
        for msg in msgs:
            append(session_path, msg)

    old_settings = termios.tcgetattr(sys.stdin)

    try:
        tty.setcbreak(sys.stdin)
        while True:
            # Read input
            prompt = _readline()

            if prompt is None:
                # ESC pressed — exit
                return

            # Non-empty prompt = add to context
            if prompt.strip():
                human_msg = add_message([], prompt)[0]
                append(session_path, human_msg)
                msgs.append(human_msg)
                continue

            # Empty prompt = one turn
            # Show loading indicator until first token arrives
            rendered: list[str] = []
            first_token = True

            def receive_character(
                character: str, _rendered: list[str] = rendered
            ) -> None:
                nonlocal first_token
                if first_token:
                    first_token = False
                _rendered.append(character)
                live.update(Markdown("".join(_rendered)))

            _clear_line()
            with Live(
                Spinner("dots", text="thinking", style="dim"),
                console=console,
                refresh_per_second=10,
                vertical_overflow="visible",
            ) as live:
                response, msgs = stream_turn(msgs, config, receive_character)
                # Tool-call responses may contain no tokens. Remove the spinner
                # rather than leaving it behind in the conversation transcript.
                if first_token:
                    live.update("")

            # Display concise tool calls in a managed Live region. Updating the
            # region, rather than moving the terminal cursor, is deterministic
            # even when a call contains long or multiline arguments.
            if response.tool_calls:
                # Models can occasionally emit the same call more than once.
                # Collapse exact duplicates so the user approves it only once.
                tool_calls = []
                seen_calls = set()
                for tc in response.tool_calls:
                    signature = (tc["name"], repr(sorted(tc.get("args", {}).items())))
                    if signature not in seen_calls:
                        seen_calls.add(signature)
                        tool_calls.append(tc)

                tool_lines = []
                for tc in tool_calls:
                    name = tc["name"]
                    args = tc.get("args", {})
                    if name == "cmd":
                        label = f"$ {args.get('command', '')}"
                        style = "yellow"
                    else:
                        label = f"{name} {args.get('path', '')}".rstrip()
                        style = "cyan"
                    tool_lines.append(Text(label, style=style))

                instruction = Text(
                    "Enter=allow  /v=view  /e=extract command  text=cancel", style="dim"
                )
                with Live(
                    Group(*tool_lines, instruction),
                    console=console,
                    refresh_per_second=10,
                    vertical_overflow="visible",
                ) as approval:
                    decision = _tool_prompt(tool_calls, console, approval)
                    if decision == "accept":
                        results = []
                        for tc in tool_calls:
                            tm = execute_tool(
                                {"name": tc["name"], "args": tc["args"], "id": tc["id"]}
                            )
                            if tc["name"] == "cmd":
                                results.extend([
                                    Text(f"$ {tc['args'].get('command', '')}", style="yellow"),
                                    Text(tm.content),
                                ])
                            tool_msg = tool_result([], tm)[0]
                            append(session_path, tool_msg)
                            msgs.append(tool_msg)
                        approval.update(Group(*results))
                    elif decision.startswith("cancel:"):
                        instruction_text = decision.removeprefix("cancel:")
                        for tc in tool_calls:
                            cancelled = ToolMessage(
                                content="tool call cancelled by user",
                                tool_call_id=str(tc["id"]),
                                name=str(tc["name"]),
                                status="error",
                            )
                            append(session_path, cancelled)
                            msgs.append(cancelled)
                        user_msg = add_message([], instruction_text)[0]
                        append(session_path, user_msg)
                        msgs.append(user_msg)
                        approval.update(Text("Tool calls cancelled", style="red"))

            console.print()  # blank line before next prompt

    except (KeyboardInterrupt, EOFError, SystemExit):
        pass
    finally:
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)


if __name__ == "__main__":
    main()
